### ISSUE TITLE
Optional features have no intellisense in VSCode

### ISSUE THREAD

**Issue by dbidwell94** [rust-analyzer/rust-analyzer#10006]
When building a WASM project, a lot of the dependencies use optional features (crate web_sys). When using an optional feature, VSCode intellisense does not work and there is no code completion. 

Example: 
```toml
[dependencies]
wasm-bindgen = "*"
web-sys = {version = "*", features = ["Window", "WebSocket"]}
js-sys = "*"
chrono = "*"

[lib]
crate-type = ["cdylib", "rlib"]
```

When the above dependencies are used as such:

```rust
use web_sys::window;

pub fn test_intellisense() {
    let w = window().unwrap();
}
```

doing anything with the new `w` variable will result in no intellisense being given. 
![image](https://user-images.githubusercontent.com/25497078/130532977-ca34aed1-d58c-4506-841c-d03eb54eddb8.png)
