### ISSUE TITLE
Panic: Failed to lookup BLOCK_EXPR@5844..5870 in this Semantics.

### ISSUE THREAD

**Issue by tekul** [rust-analyzer/rust-analyzer#10475]
I'm using rust-analyzer-preview with nightly on Linux and see this error for a particular line in my project. It's always reproducible (I'm using neovim with the builtin LSP - not sure if that's a factor or how to run rust-analyzer independently). I noticed some issues with a similar message but they are either closed or apparently hard to reproduce. I get this every time.

Versions:
```
rust-analyzer 4b7675f 2021-10-05 dev
rustc 1.57.0-nightly (25ec82738 2021-10-05)
```
I can reduce it to the following:

```toml
[package]                                                      
name = "rapanic"                                        
version = "0.1.0"                                  
edition = "2021"                                   

[dependencies]
rand = "0.8"
```

```rust
fn main() {                                                    
   let _x = rand::random::<[u8; 8]>();      
}
```
Error I get when I move cursor to the word `random`:

```
LSP[rust_analyzer] server panicked:                                                                                            
Failed to lookup BLOCK_EXPR@5844..5870 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..6713
known nodes: SOURCE_FILE@0..54
```
Which seems to come from [here](https://github.com/rust-analyzer/rust-analyzer/blob/bcf04b19f80a77353c54b5919897ed5c5087687e/crates/hir/src/semantics.rs#L899) but I don't have a stack trace for how it gets there.

Let me know if (and how) I can provide more information.
