### ISSUE TITLE
No auto-completion inside fn (& attribute proc-macro)

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#10520]
```rust
use tracing::instrument;

#[instrument]
fn testy() {
    let x = Vec::new();
    x.<|> // no auto completions here
}
```

```toml
[dependencies]
tracing = { version = "0.1.29", features = ["attributes"] }
```

rust-analyzer: 1e9ecb9f5859afcca31b0c130b0b81325036e5a6 (master)

rust-analyzer should be able to trigger auto-completions at that position even with an attribute proc-macro at fn level (hover information works though).

![image](https://user-images.githubusercontent.com/5961244/136815905-2f8b8706-1b40-4e5c-92bd-0934ace3873f.png)
