### ISSUE TITLE
Trait method not recognized and type not inferred

### ISSUE THREAD

**Issue by PorkSausages** [rust-analyzer/rust-analyzer#11076]
**rust-analyzer version**: 0add6e95e 2021-12-20 stable

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

I'm not sure what it is about this method that RA can't recognize, but here's an easily reproducible example:

Cargo.toml:
```toml
[package]
name = "ra-bug-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10.0"
```

main.rs:
```rust
use async_std::{
    net::{TcpListener},
    prelude::*,
    task,
};

fn main() {
    task::block_on(run("127.0.0.1:8000"));
}

async fn run(addr: &str) {
    let listener = TcpListener::bind(addr)
        .await
        .expect("Error binding TCP listener");

    // Here .next() is totally unrecognized and _stream is {unknown}
    while let Some(_stream) = listener.incoming().next().await {
        println!("Incoming!");
    }
}
```
