### ISSUE TITLE
Failed to "Run Test": run Cargo from wrong folder

### ISSUE THREAD

**Issue by MoGuGuai-hzr** [rust-analyzer/rust-analyzer#11834]
# summary

IDE: vscode
Analyzer Version: v0.2.993
A. No run commands are shown in the rust subfile, e.g. "Run test". Does this file have to be depended on?
B. The analyzer fails to run command in subfiles, such as test command.

# Build test environment
```
> cargo new example
> cd example
example > cargo new --lib crates/worker
```

## files structure
```
example > tree -I target
.
├── Cargo.lock
├── Cargo.toml
├── crates
│   └── worker
│       ├── Cargo.toml
│       └── src
│           └── lib.rs
└── src
    └── main.rs

4 directories, 5 files
```

## lib.rs
```rust
// example > cat crates/worker/src/lib.rs
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        let result = 2 + 2;
        assert_eq!(result, 4);
    }
}
```

# Issue A
Open the folder example in vscode, but no run commands are shown in the rust `crates/worker/src/lib.rs`.

It appears after modifying dependencies.

Raw `Cargo.toml`:
```toml
# example > cat Cargo.toml 
[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

Add dependencies:
```toml
# example > cat Cargo.toml 
[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
worker = {path = "crates/worker"}
```

Now, I can run command "Run Test" in `crates/worker/src/lib.rs`.
But it fails.

# Issue B
The analyzer fails to run command "Run Test" in `crates/worker/src/lib.rs`.
This is similar to issue #7764.

Result:
```
> Executing task: cargo test -- tests::it_works --exact --nocapture <

error: could not find `Cargo.toml` in `/` or any parent directory
The terminal process "cargo 'test', '--', 'tests::it_works', '--exact', '--nocapture'" failed to launch (exit code: 101).

Terminal will be reused by tasks, press any key to close it.
```
