### ISSUE TITLE
Cargo.toml files using absolute paths are not correctly parsed

### ISSUE THREAD

**Issue by gbbosak** [rust-analyzer/rust-analyzer#2434]
On Fuchsia; we use a gen-cargo script to generate Cargo.toml files from our custom build system that are compatible with RLS. These files use absolute paths to their dependencies, and this seems to break rust-analyzer, but functions just fine with RLS.

Steps to repro:
* Download Fuchsia (see here): https://fuchsia.dev/fuchsia-src/development/source_code
* fx set core.x64 --release
* fx build (this may take several hours, and requires a pretty powerful machine)
* fx gen-cargo //src/connectivity/bluetooth/profiles/bt-a2dp-sink:bin
* Open fuchsia/src/connectivity/bluetooth/profiles/bt-a2dp-sink in an editor that supports rust-analyzer (such as VSCode)
* Observe  errors such as this "Unable to open 'channel.rs': Unable to read file (Error: File not found (/mntpnt/fuchsia/src/connectivity/bluetooth/profiles/bt-a2dp-sink/mntpnt/fuchsia/garnet/public/rust/fuchsia-zircon/src/channel.rs))."
when trying to navigate between files with rust-analyzer.

**Comment by edwin0cheng** [comment]
I did try to replicate your case with a full path deps and it works :

```toml
# /sandbox/temp/foo/crates/foo.toml

[package]
name = "foo"
version = "0.1.0"
authors = ["Edwin Cheng <edwin0cheng@gmail.com>"]
edition = "2018"

[dependencies]
baz = {path="/sandbox/temp/foo/crates/baz"}
```
Would you mind to just share the post-generated Cargo.toml ?
