### ISSUE TITLE
Problem parsing emacs initializing request

### ISSUE THREAD

**Issue by samanpa** [rust-analyzer/rust-analyzer#3123]
RLS seems to be having issues converting the initializing message `lsp_types::InitializeParams` that it gets from my emacs installation.

The error it gets is `Error("invalid type: null, expected a boolean", line: 0, column: 0)`.

Please find the gist below that contains the reproducer.
https://gist.github.com/samanpa/7bb31219b53e803e11cee26de8de7b1a

The error goes away when `lsp-types` is compiled without the `proposed` feature.

Problematic toml
```toml
[dependencies]
lsp-types = { version = "0.70", features = ["proposed"] }
serde = {version = "1.0", features = [ "derive" ]}
serde_json = "1.0"
```

Working toml
```toml
[dependencies]
lsp-types = { version = "0.70" }
serde = {version = "1.0", features = [ "derive" ]}
serde_json = "1.0"
```
