### ISSUE TITLE
rust-analyzer in `tests` directory in submodule (workspace)

### ISSUE THREAD

**Issue by olvyko** [rust-analyzer/rust-analyzer#3567]
I have project with structure like this 
```
modules
├─ module1
│  ├─ src
│  └─ tests
src
tests
```
and I can’t get `rust-analyzer` error highlighting to work in submodule(module1) tests folder.
In root tests folders its works.

**Comment by olvyko** [comment]
> How is modules directory hooked up into a cargo project?

Like that, root Cargo.toml
```toml
[dependencies]
module1 = { path = "modules/module1" }

[workspace]
members = [
    "modules/module1",
]
```
