### ISSUE TITLE
Optional features doesn't seem to work

### ISSUE THREAD

**Issue by c410-f3r** [rust-analyzer/rust-analyzer#3585]
Maybe it is just me getting crazy.

The following:

```toml
[package]
name = "example"
version = "0.1.0"

[features]
alloc = []
default = []
```

```rust
#[cfg(feature = "alloc")]
extern crate alloc;

fn main() {
    let _ = alloc::vec::Vec::<i32>::new();
}
```

Doesn't work with ` "rust-analyzer.cargoFeatures.allFeatures": true` or ` "rust-analyzer.cargoFeatures.allFeatures": false, "rust-analyzer.cargoFeatures.features": ["alloc"]`

A screenshot for illustration.

![Capture d’écran de 2020-03-13 14-28-27](https://user-images.githubusercontent.com/17877264/76645094-05045c80-6537-11ea-98ee-323520cf316b.png)
