### ISSUE TITLE
Enable running nightly rustfmt

### ISSUE THREAD

**Issue by khyperia** [rust-analyzer/rust-analyzer#3627]
Some rustfmt.toml configurations (in my case, `merge_imports = true`) are only available when running nightly rustfmt, they're not available in stable. So, we should allow users to select what channel to run rustfmt under. Thanks! :sparkles:

I think the relevant code is here https://github.com/rust-analyzer/rust-analyzer/blob/46c618f7d989849cae11c7e4b7b7370bf89faaa2/xtask/src/lib.rs#L45

**Comment by kiljacken** [comment]
You should be able to pass "+nightly" using the `rustfmtArgs` config in VSCode

**Comment by khyperia** [comment]
Hmm. Doing so seems to not change anything. I noticed there's another way in the codebase that rustfmt is invoked, https://github.com/rust-analyzer/rust-analyzer/blob/a99cac671c3e6105a0192acbb1a91cb83e453018/crates/rust-analyzer/src/main_loop/handlers.rs#L613, does calling `rustfmt` directly parse `.rustfmt.toml`? that's my only guess as to why it's not working.

**Comment by khyperia** [comment]
Ah, a restart of vscode was required. Thanks for your help!

**Comment by Veetaha** [comment]
We might want to add `rustFmtArgs` entry here:
https://github.com/rust-analyzer/rust-analyzer/blob/46c618f7d989849cae11c7e4b7b7370bf89faaa2/editors/code/src/config.ts#L38

**Comment by khyperia** [comment]
Note to people finding this issue on google: a lot of config settings got renamed/changed, and the above no longer works. I was able to get it working again with https://github.com/rust-analyzer/rust-analyzer/issues/3916 :

```json
"rust-analyzer.rustfmt.overrideCommand": [
  "rustup",
  "run",
  "nightly",
  "--",
  "rustfmt",
  "--edition",
  "2018",
  "--"
],
```

**Comment by willmcpherson2** [comment]
For those using `init.lua`, you can try this:

```lua
lspconfig.rust_analyzer.setup {
    settings = {
        ["rust-analyzer"] = {
            rustfmt = {
                extraArgs = { "+nightly", },
            },
        }
    }
}
```

**Comment by GilShoshan94** [comment]
No need to modify `rust-analyzer.rustfmt.overrideCommand`, the "+nightly" works.
Here bellow a full "How to" for others.

First, make sure you have the nightly rustfmt installed. It can be done easily with rustup:
\> `rustup toolchain install nightly`

Than, for vscode, in `settings.json`
```json
"rust-analyzer.rustfmt.extraArgs": [
        "+nightly"
    ],
```

Finally, in the project dir, we can use a the "unstable_features`" by activating them in a `rustfmt.toml` file.
Here is mine as example:
```toml
# I can't rely on contributors using .editorconfig
newline_style = "Unix"
# require the shorthand instead of it being optional
use_field_init_shorthand = true
# outdated default — `?` was unstable at the time
# additionally the `try!` macro is deprecated now
use_try_shorthand = true
# Max to use the 100 char width for everything or Default. See https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#use_small_heuristics
use_small_heuristics = "Max"

# Unstable features below
unstable_features = true
version = "Two"
# code can be 100 characters, why not comments?
comment_width = 100
# force contributors to follow the formatting requirement
error_on_line_overflow = true
error_on_unformatted = true
# next 4: why not?
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
# better grepping
imports_granularity = "Module"
# quicker manual lookup
group_imports = "StdExternalCrate"
# why use an attribute if a normal doc comment would suffice?
normalize_doc_attributes = true
# why not?
wrap_comments = true
```

(The `version = "Two"` is just required as written in rustfmt documentation)
