### ISSUE TITLE
Formating don't work for module under the #[cfg(feature = "test_feature")]

### ISSUE THREAD

**Issue by olvyko** [rust-analyzer/rust-analyzer#3818]
I noticed that formating of file don't work for module under the `#[cfg(feature = "test_feature")]` macro.
```rust
#[cfg(feature = "test_feature")]
pub mod module1;
```
```toml
[package]
name = "package"
version = "0.1.0"
edition = "2018"

[features]
default = []
test_feature = []
```
Code in `module1` won't be formatted ... at the same time, `analyzer` shows errors in this module.
I'm not sure if this is an `analyzer` issue, maybe is `rustfmt` issue?
