### ISSUE TITLE
Unknown types in web-sys dependency

### ISSUE THREAD

**Issue by eminence** [rust-analyzer/rust-analyzer#4150]
(I suspect this is a duplicate, but i'm not sure what the root cause is).

I'm trying to use the [web-sys](https://crates.io/crates/web-sys) crate, which is highly generated.

I've enabled both `loadOutDirsFromCheck` and `procMacro.enable`:

<details><summary>.vscode/settings.jon</summary>

```json
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
    "editor.tokenColorCustomizationsExperimental": {
        "unresolvedReference": "#FF0000"
    }
}
```

</details>

<details><summary>Cargo.toml</summary>

```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Andrew Chin <achin@eminence32.net>"]
edition = "2018"

[dependencies.web-sys]
version = "0.3"
features = ["Document", "Window"]

```

</details>

Code:

```rust
use web_sys::{Document, Window};

pub fn foo() {
    let win: Window = web_sys::window().unwrap();
    let doc: Document = win.document().unwrap();
}
```
![image](https://user-images.githubusercontent.com/402454/80298125-3a67b100-8757-11ea-8058-d46375aab375.png)

Using RA nightly (fe99a29)

Thanks!
