### ISSUE TITLE
Module alias misidentified as function declaration

### ISSUE THREAD

**Issue by CleanCut** [rust-analyzer/rust-analyzer#4202]
With `Cargo.toml`:
```toml
[dependencies]
nalgebra-glm = { version = "0.6.0", features = ["serde-serialize"] }
```

In `src/lib.rs`:
```rust
pub use nalgebra_glm as glm;
```

`glm` is identified as a function declaration.  It is a module alias, so it should be identified as a `namespace`, probably with some sort of `alias` modifier.

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/5838512/80563377-3b435180-89a8-11ea-8303-578bd544eafe.png">
