### ISSUE TITLE
Rust-analyser not processing results from next() method of async_std::stream::StreamExt

### ISSUE THREAD

**Issue by SillyMoo** [rust-analyzer/rust-analyzer#4243]
Rust analyser is not able to process the next() method at the end of the attached rust file. This works ok with vs-code and rls, but vs-code with rust-analyzer it fails to return a type for the result of next().

[src.zip](https://github.com/rust-analyzer/rust-analyzer/files/4564747/src.zip)

**Comment by bjorn3** [comment]
Maybe a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1791? (`async`/`await` support)

<details><summary>Content of the zip, for mobile users</summary>

```rust
use async_amqp::*;
use async_std::stream::StreamExt;
use lapin::{
    message::DeliveryResult, options::*, publisher_confirm::Confirmation, types::FieldTable,
    BasicProperties, Connection, ConnectionProperties, Result,
};
use log::info;
use futures::channel::mpsc;
use futures::sink::SinkExt;

struct TaskProperty {
    name: String,
    sval: Option<String>,
    nval: Option<i32>,
}
struct Task {
    task_id: String,
    task_ulid: String,
    sample_id: String,
    vm_profile: String,
    task_properties: Vec<TaskProperty>,
}

#[async_std::main]
async fn main() -> Result<()> {

    env_logger::init();
    
    let (tx, mut rx)= mpsc::channel::<String>(100);


    let addr = "amqp://localhost:5673";
    let conn = Connection::connect(&addr, ConnectionProperties::default().with_async_std()).await?;
    let queue_name = "bob";
    info!("CONNECTED");

    let channel_a = conn.create_channel().await?;
    let channel_b = conn.create_channel().await?;

    let queue = channel_a
        .queue_declare(
            queue_name,
            QueueDeclareOptions::default(),
            FieldTable::default(),
        )
        .await?;

    info!("Declared queue {:?}", queue);

    let consumer = channel_b
        .clone()
        .basic_consume(
            queue_name,
            "my_consumer",
            BasicConsumeOptions::default(),
            FieldTable::default(),
        )
        .await?;

    consumer.set_delegate(move |delivery: DeliveryResult| {
        let channel_b = channel_b.clone();
        let mut tx = tx.clone();
        async move {
            let delivery = delivery.expect("error caught in in consumer");
            if let Some(delivery) = delivery {
                channel_b
                    .basic_ack(delivery.delivery_tag, BasicAckOptions::default())
                    .await
                    .expect("failed to ack");
                tx.send(String::from_utf8(delivery.data).unwrap()).await.unwrap();
            }
        }
    });

    let payload = b"Hello world!";

    
    let confirm = channel_a
        .basic_publish(
            "",
            queue_name,
            BasicPublishOptions::default(),
            payload.to_vec(),
            BasicProperties::default(),
        )
        .await?
        .await?;
    assert_eq!(confirm, Confirmation::NotRequested);
    let res = rx.next().await.unwrap();
    info!("Got {:?}", res);
    Ok(())
}
```

```toml
[package]
name = "ivm2_rust"
version = "0.1.0"
authors = ["Chris Mills <Chris_Mills@symantec.com>"]
edition = "2018"

[dependencies]
smol = "0.1.4"
log = "0.4.8"
async-amqp = "0.1.0-beta3"
env_logger = "0.7.1"
futures = "0.3.4"

[dependencies.async-std]
version = "^1.0"
features = ["default"]

[dev-dependencies.async-std]
version = "^1.0"
features = ["attributes", "default"]

[dependencies.lapin]
version = "1.0.0-beta3"
default-features = true
```

</details>
