### ISSUE TITLE
Macro imports are not highlighted

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#4462]
RA version: current freshmost master, `unreleased (05db35d)`
VSCode theme `Dark+ (default dark)` is used

`Cargo.toml`:
```toml
[package]
name = "macro-test"
version = "0.1.0"
edition = "2018"

[dependencies]
maplit = "1.0"
```

`main.rs`:
```rust
use maplit::hashset;

fn main() {
    let set = hashset![1, 2, 3];
    dbg!(set);
}
```

Expected: everything is highlighted
Actual: macro import is not highlighted

<img width="662" alt="image" src="https://user-images.githubusercontent.com/2690773/82031175-2225ea80-96a2-11ea-8b50-c538debc3432.png">
<img width="755" alt="image" src="https://user-images.githubusercontent.com/2690773/82031182-25b97180-96a2-11ea-8f10-1b23d4a2329b.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/2690773/82031189-26ea9e80-96a2-11ea-9248-b465fafe4c91.png">

It would be great to highlight the macro imports the same way we highlight the macro usages in the code.
