### ISSUE TITLE
cfg_attr condition is ignored

### ISSUE THREAD

**Issue by RReverser** [rust-analyzer/rust-analyzer#4707]
Take a look at this simplest `lib.rs`:

```rust
#![cfg_attr(feature = "nightly", feature(never_type))]

pub fn foo() {}
```

Cargo.toml:

```toml
[package]
name = "ra-test"
version = "0.1.0"
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
edition = "2018"

[features]
default = []
nightly = []
```

Workspace settings:

```json
{
	"rust-analyzer.cargo.allFeatures": false
}
```

I'm getting an error on the first line of `lib.rs` saying

> `#![feature]` may not be used on the stable release channel rustc(E0554)

This `feature` should never be activated, because it's not explicitly set and `allFeatures` is also `false`. I also think that I didn't see this error on the same condition in the past (around ~2 months ago), but hard to tell for sure.
