### ISSUE TITLE
Autocomplete crate features

### ISSUE THREAD

**Issue by chinedufn** [rust-analyzer/rust-analyzer#5398]
Would be nice if

```toml
# Cargo.toml for Some Crate

[features]
default = []
crossbeam-channel = ["crossbeam-channel"]
```

```rust
// Source code file within Some Crate

#[cfg(feature = "cr<|>")]
fn foo () {
}
```

Autocompleted to `#[cfg(feature = "crossbeam-channel")]`
