### ISSUE TITLE
auto_complete does not work with conditional compilation

### ISSUE THREAD

**Issue by seanybaggins** [rust-analyzer/rust-analyzer#5731]
source
-------
![image](https://user-images.githubusercontent.com/18423154/90049543-2dcd8100-dc92-11ea-85e6-9a498aa131f4.png)

cargo.toml
------------
```toml
[package]
name = "auto_complete"
version = "0.1.0"
authors = ["seanybaggins <seli2854@colorado.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
foo = []

[dependencies]
```
