### ISSUE TITLE
Upgrading 2020-09-14 -> 2020-09-21 broke #![feature(rustc_private)]

### ISSUE THREAD

**Issue by khyperia** [rust-analyzer/rust-analyzer#6057]
## Setup

Cargo.toml:

```toml
[package]
name = "nightlytest"
version = "0.1.0"
authors = ["khyperia <github@khyperia.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
```

rust-toolchain:
```
nightly
```

src/lib.rs:
```rust
#![feature(rustc_private)]

extern crate rustc_ast;
```

## Expected behavior, behavior on rust-analyzer 2020-09-14

No error

## Actual behavior on rust-analyzer 2020-09-21

Red squiggles on the extern crate, with popup `unresolved extern crate`. `cargo build` etc. still works fine.
