### ISSUE TITLE
Read rust-analyzer configuration from Cargo.toml?

### ISSUE THREAD

**Issue by cuviper** [rust-analyzer/rust-analyzer#6113]
Would it be possible to read configuration options from `Cargo.toml`? Then they could be specified in an editor-neutral way, something like:

```toml
[package.metadata.rust-analyzer.cargo]
noDefaultFeatures = true
features = ["foo", "bar"]
```

I think snake-case would be more idiomatic for `Cargo.toml`, but I don't know how deep we'd want to get into translating names. There's also a mismatch between the usual `default_features = false` and RA's `noDefaultFeatures`.
