### ISSUE TITLE
Do not terminate on non-existant dependency

### ISSUE THREAD

**Issue by drahnr** [rust-analyzer/rust-analyzer#6119]
In vscode, the whole extension host is taken down, if a mistyped/non-existant dependency is specified.

```toml
#Cargo.toml
[dependencies]
fffffffff = "1.0"
```
