### ISSUE TITLE
Tests with required features are not detected

### ISSUE THREAD

**Issue by nox** [rust-analyzer/rust-analyzer#6505]
I have the following block in my Cargo.toml file:

```toml
[[example]]
name = "say-it-thrice"
path = "tests/say-it-thrice.rs"
required-features = ["std"]
```

And the following config in my workspace:

```json
{
    "rust-analyzer.cargo.features": [
        "std",
    ]
}
```

When I open tests/say-it-trice.rs, there is no "Run | Debug" action showing until I remove the `example` block from the Cargo manifest file, that seems like a bug to me.
