### ISSUE TITLE
Module resolution fails when using non-standard filenames.

### ISSUE THREAD

**Issue by regiontog** [rust-analyzer/rust-analyzer#668]
When using a combination of directory modules and a name other than lib.rs/main.rs module resolution fails.

Cargo allows you to have a name other than e.g. lib.rs for libraries like this.

```toml
[package]
...

[lib]
path = "src/my_library.rs"
``` 

Relevant code:
https://github.com/rust-analyzer/rust-analyzer/blob/2acaa92c93bcd54d97221d0cede8780ff817476e/crates/ra_hir/src/module_tree.rs#L291-L306
