### ISSUE TITLE
scopeguard::defer macro invocation failed to parse

### ISSUE THREAD

**Issue by Krysme** [rust-analyzer/rust-analyzer#6704]
There is an error while I'm trying to invoke a macro from `scopeguard`.
This one is easy to be reproduced on my machine.

here is the source code to reproduce it:

Cargo.toml
```toml
[package]
name = "macro-err"
version = "0.1.0"
authors = ["foo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scopeguard = "*"

```

src/main.rs
```rust
use scopeguard::defer;

fn main() {
    defer!({
        println!("exit");
    });
    println!("Hello, world!");
}

```

With this source code, I have `failed to parse macro invocation [macro-error]`
