### ISSUE TITLE
rust-analyzer is showing a type that Rust cannot infer

### ISSUE THREAD

**Issue by xFrednet** [rust-analyzer/rust-analyzer#6709]
I'm using rust-analyzer with VS-Code. I had a bug where rust-analyzer was displaying a type in the inline tip but the Rust compiler was producing the error `error[E0282]: type annotations needed`

The inline tip:
![image](https://user-images.githubusercontent.com/17087237/101022370-37dcfd80-3569-11eb-93c6-838db5bb0309.png)

The compiler error:
![image](https://user-images.githubusercontent.com/17087237/101022428-4cb99100-3569-11eb-842a-7068729c8b1d.png)

The inline tip is correct but Rust is not recognizing the correct type. This is currently a mismatch between the compiler and rust-analyzer. I would expect rust-analyzer show where the error originates from and suggest the fix of adding the type annotation. 

Keep up the good work! 🙃 

---
System information:

| What                | Version                      | Note                                                            |
| ------------------- | ---------------------------- | --------------------------------------------------------------- |
| rustc               | `1.48.0`                       | I've also tested this with version 1.47.0                       |
| tookchain           | `stable-x86_64-pc-windows-gnu` |                                                                 |
| rust-analizer addon | `0.2.400`                      |                                                                 |
| rust-analizer       | ---                          | I sadly couldn't find the version but I've updated it recently. I can add it if you let me know where I can find this information :) |
| VS-Code             | `1.51.1`                       |                                                                 |

* Other installed addons that might be interesting:
    * Better TOML `0.3.2`
    * crates `0.5.3`
    * Search crates.io `1.2.1`

---

<details>
<summary>Minimal example:</summary>

Cargo.toml:
```toml
[package]
name = "lab"
version = "0.1.0"
authors = ["xFrednet <xFrednet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
```

main.rs
```rust
use std::error::Error;
use std::fs::File;
use std::io::BufReader;
use std::path::Path;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Config {
    name: String
}

impl Config {
    fn configure(&mut self) {}
}

fn load_config<P: AsRef<Path>>(path: P) -> Result<Config, Box<dyn Error>> {
    let file = File::open(path)?;
    let reader = BufReader::new(file);

    // Read the JSON contents of the file as an instance of `Config`.
    let mut con = serde_json::from_reader(reader)?;

    con.configure();

    Ok(con)
}

fn main() {
    let _a = load_config("some_file.json");
}
```
</details>
