### ISSUE TITLE
"could not resolve macro" in a working crate

### ISSUE THREAD

**Issue by osa1** [rust-analyzer/rust-analyzer#6950]
rust-analyzer version: df3652b66

In a crate that builds and runs fine (using latest stable release) rust-analyzer raises an error. crate code:

<details>

<summary>Cargo.toml</summary>

```toml
[package]
name = "macro_test"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
maplit = "1.0.2"
```

</details>

<details>

<summary>main.rs</summary>

```rust
use maplit::hashmap;
use std::collections::HashMap;

fn main() {
    let _: HashMap<usize, Vec<usize>> = hashmap! {
        1 => vec![]
    };
}
```

</details>

rust-analyzer error:

![Screenshot_2020-12-19_17-59-05](https://user-images.githubusercontent.com/448274/102692412-172ccd00-4224-11eb-8117-cf4b373accf6.png)
