### ISSUE TITLE
Fully qualified proc-macros are classified as functions

### ISSUE THREAD

**Issue by AdnoC** [rust-analyzer/rust-analyzer#7114]
Related: https://github.com/rust-analyzer/rust-analyzer/issues/6881
Related: https://github.com/rust-analyzer/rust-analyzer/issues/7073

Classification obtained by wrapping https://github.com/rust-analyzer/rust-analyzer/blob/339aab37744e7bfcab1def72acb26b81da6408ce/crates/ide/src/goto_definition.rs#L115-L118 in a `dbg!()` and running `rust-analyzer analysis-bench src/main.rs --goto-def src/main.rs:6:5` and `rust-analyzer analysis-bench src/main.rs --goto-def src/main.rs:9:15`.

src/main.rs:
```rust
// using the unzip-n crate

use unzip_n::unzip_n;

//  Classification: `Definition(Macro(MacroDef { id: MacroDefId { krate: CrateId(53), ast_id: None, kind: ProcMacro(ProcMacroExpander { krate: CrateId(53), proc_macro_id: None }), local_inner: false } }))`
unzip_n!(3);

// Classification `Definition(ModuleDef(Function(Function { id: FunctionId(1115) })))`
unzip_n::unzip_n!(4);

fn main() {}
```

Cargo.toml:

```toml
[package]
name = "ratest"
version = "0.1.0"
authors = ["AdnoC <adam.r.cutler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unzip-n = "0.1.2"
```
