### ISSUE TITLE
required features of dependencies in examples 

### ISSUE THREAD

**Issue by Maan2003** [rust-analyzer/rust-analyzer#7118]
`some_feature` of `a` is not enabled in `examples/example.rs` file.
```toml
[[example]]
name = "example"
required-features = ["a/some_feature"] 
```
[Minimal, Reproducible Example](https://github.com/rust-analyzer/rust-analyzer/files/5758777/ra-example-feature-mre.zip)

extension version: 0.2.432 stable
server version: 1d53075
