### ISSUE TITLE
Macro errors in working code (rust-analyzer master, 90ccf4f5adf)

### ISSUE THREAD

**Issue by osa1** [rust-analyzer/rust-analyzer#7214]
Tried with 5fe8cb1fb (current master).

Cargo.toml:

```toml
[package]
name = "macro_test"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
tokio = { version = "0.3.6", features = ["time"] }
```

main.rs:

```rust
use futures::future::Fuse;
use futures::select;
use tokio::time::Sleep;

fn main() {}

async fn _test(mut x: Fuse<Sleep>, mut y: Fuse<Sleep>) {
    select! {
        () = x => {},
        () = y => {},
    }
}
```

Error:

![Screenshot_2021-01-09_11-31-27](https://user-images.githubusercontent.com/448274/104087079-39879880-526e-11eb-8bf1-ae433b1fb44e.png)
