### ISSUE TITLE
Taking a really long time to load in vim

### ISSUE THREAD

**Issue by wantyapps** [rust-analyzer/rust-analyzer#7682]
When opening a rust file in vim, the autocompletions and debugger takes a LOT of Time (20secs) to load.

BTW: There is another error when in string, completions like `const`, `let` and stuff appear

**Comment by bjorn3** [comment]
How big is your project? For bigger projects it takes a while before it is indexed. In VS Code it shows the progress in the status bar. Depending on the LSP extension you use, you may also see this.

**Comment by wantyapps** [comment]
it is nothing

**Comment by wantyapps** [comment]
really small

**Comment by wantyapps** [comment]
only main.rs and Cargo stuff

**Comment by bjorn3** [comment]
What dependencies do you use?

**Comment by wantyapps** [comment]
nvim-lspconfig

**Comment by wantyapps** [comment]
my dotfiles are in https://github.com/wantyapps/dotfiles

**Comment by wantyapps** [comment]
The lsp settings are at the bottom of the plug_config.vim file

**Comment by wantyapps** [comment]
wait what do you mean dependencies?

**Comment by lnicola** [comment]
External crates in your `Cargo.toml`, under `[dependencies]` or `[dev-dependencies]`.

**Comment by wantyapps** [comment]
This is my cargo.toml:
```toml
[package]
name = "debugcli"
version = "0.1.0"
authors = ["Uri Arev <uri.arev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```
