### ISSUE TITLE
"Failed to parse macro invocation" when using crate "proconio"

### ISSUE THREAD

**Issue by baku1101** [rust-analyzer/rust-analyzer#8171]
proconio is easy IO library for competitive programming.

Error occur when using `input!` macro.

I can compile and run it, but I get "Failed to parse macro invocation" in rust-analyzer.

This error was confirmed in both vim and vscode.

rust-analyzer is nightly version(0.3.528).

![image](https://user-images.githubusercontent.com/29083301/112180252-ba83e880-8c3e-11eb-99c3-ae2d3d45cb63.png)

## Complete repro

cargo.toml:

```toml
[package]
name = "repro"
version = "0.1.0"
authors = ["hogehoge"]
edition = "2018"
[dependencies]
proconio = "0.4.2"
```

main.rs

```rust
use proconio::*;
fn main() {
    input! {
        _n: isize,
    }
}
```

Thank you.
