### ISSUE TITLE
rust-analyzer reports proc-macro panic while rustc doesn't

### ISSUE THREAD

**Issue by tirr-c** [rust-analyzer/rust-analyzer#8202]
`Cargo.toml`:
```toml
[package]
name = "proc-macro-test"
version = "0.1.0"
edition = "2018"

[dependencies]
derive_builder = "0.9.0"
```

`src/lib.rs`:
```rust
#[derive(Default, derive_builder::Builder)]
#[builder(default)]
struct Foo {}
```

## Expected
rust-analyzer reports no errors on `src/lib.rs`.

## Actual
rust-analyzer reports an error with message: ``proc macro returned error: proc-macro panicked: Couldn't parse default expression `Trait`: "expected curly braces"``.

`cargo check` passes.

## Meta

* Server version: `rust-analyzer 60c501f`
* `rustc` version: `rustc 1.51.0 (2fd73fabe 2021-03-23)`
