### ISSUE TITLE
How do I make rust-analyzer not attempt to build the test crate or tests in my embedded project?

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#8288]
I'm tearing my hair out trying to get rust-analyzer to work for my embedded project without it trying to build the `test` crate (which doesn't exist and then the build crashes)

My `.cargo/config.toml` file looks like this:
```toml
[build]
target = "thumbv4t-none-eabi"

[unstable]
build-std = ["core"]

[target.thumbv4t-none-eabi]
rustflags = ["-Clink-arg=-Tlinker.ld"]
runner = "mgba"
```

So I'm already getting the compilation target selected, and I have my `.vscode/settings.json` as:
```json
{
  "rust-analyzer.checkOnSave.command": "build --examples",
  "rust-analyzer.checkOnSave.allTargets": false,
}
```
but then then it still seems to want to try and build something or other that requires the `test` crate.
