### ISSUE TITLE
Multiple binaries/shared library project structure best practice

### ISSUE THREAD

**Issue by oeed** [rust-analyzer/rust-analyzer#8362]
I'm encountering bad performance penalties from what is presumably a bad project file structure.

I have a monorepo containing multiple binaries performing unrelated tasks with a `lib` folder with a bunch of crates these binaries use (each uses some but not all crates) and these lib crates have dependencies between themselves.

Here's a rough guide to the file structure:
```
binary_a/
  Cargo.toml
  src/...

binary_b/
  Cargo.toml
  src/...

lib/
  lib_a/
    Cargo.toml
    src/...

  lib_b/
    Cargo.toml
    src/...
```

A binary's Cargo.toml looks somewhat like:

```toml
[package]
name = "binary_a"

[dependencies]
lib_a = {path = "../lib/lib_a"}
```

and a library's:

```toml
[package]
name = "lib_a"

[dependencies]
lib_b = {path = "../lib/lib_b"}
```

I then have VSCode workspace for each binary that includes the binary and the `lib` folder:
```json
{
  "folders": [{
      "path": "."
    },
    {
      "path": "../lib"
    }
  ]
}
```

However, this seems to spin up a cargo check for every single crate in `lib` the binary is using and becomes almost unusably performance draining. It also seems to duplicate indexing/checking external dependencies (i.e. serde is indexed N times).

<img width="458" alt="Screen Shot 2021-04-06 at 2 59 10 PM" src="https://user-images.githubusercontent.com/3835991/113654411-d92cb980-96eb-11eb-8bc7-07b6b6f19dee.png">

I had previously use a root Cargo workspace which included every binary and library. The performance was better, although it still did two cargo checks, but editing multiple binaries at once (hence two VSCode workspaces) didn't really work as one would have a lock and the other wouldn't.

Opening just the binary folder sees much better performance but then I can easily access files in `lib` which is where 90% of the code is. I've tried finding a way to disable the plugin on just the `lib` folder but it doesn't seem possible.

-----

What's the best structure to use here? I feel like I'm definitely doing something wrong, so I'm quite happy to completely rearrange everything if required. Thanks!

**Comment by bjorn3** [comment]
You can use a cargo workspace. This will also share the target dir used by cargo for all crates. To make a cargo workspace add a file `Cargo.toml` in the root of the project with a content like:

```toml
[workspace]
include = ["binary_a", "binary_b", "lib/lib_a", "lib/lib_b"]
```
