### ISSUE TITLE
cfg calculation doesn't seem to respect `-Ctarget-cpu=native` in `.cargo/config.toml`

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#8480]
When using a `.cargo/config.toml` like the following:

```toml
[build]
# This can cause weirdness if they don't match!
rustflags = ["-Ctarget-cpu=native"]
rustdocflags = ["-Ctarget-cpu=native"]
```

RA doesn't show the additional features as being configured in, which means those functions and modules don't get and RA support at all. I know that my CPU *has* the features because `cargo test` in my terminal runs all the tests for the additional feature'd functions.
