### ISSUE TITLE
proc-macro panic with use-after-free

### ISSUE THREAD

**Issue by yisonPylkita** [rust-analyzer/rust-analyzer#9323]
Whenever I try to use rust-analyzer with proc-macros enabled there is a problem with `structopt` crate. Here is a message from rust-analyzer
```
proc macro returned error: proc-macro panicked: use-after-free in `proc_macro` handle
rust-analyzer (macro-error)
```
![image](https://user-images.githubusercontent.com/8435296/122529699-0c5dc400-d01e-11eb-90fa-f916520c1af7.png)

Here is code 
```rust
use structopt::StructOpt;

#[derive(StructOpt)]
#[structopt(name = "example", about = "An example of StructOpt usage.")]
struct Opt {}

fn main() {
    let _ = Opt::from_args();
}
```
and Cargo.toml
```toml
[package]
name = "proc-macro-debug"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = "0.3"
```

Info about my setup
System: WSL 2 Ubuntu 20.04
Editor: vscode 1.57.0
rust-analyzer extension version: v0.3.642
Tested on a nightly version downloaded by vscode 18.06.2021
