### ISSUE TITLE
False-positive when using thiserror

### ISSUE THREAD

**Issue by booleancoercion** [rust-analyzer/rust-analyzer#9495]
When using thiserror, the latest rust-analyzer nightly on VS Code reports that the `Error` proc marco panicked with this message: `proc macro returned error: proc-macro panicked: range end index 4 out of range for slice of length 0`. The previous rust-analyzer nightly could process this code correctly.

Here's the smallest example I could find (as a library crate, this is the source for `lib.rs`):
```rs
use thiserror::Error;

#[derive(Debug, Error)]
pub enum MyError {
    #[error("variant")]
    Variant,
}
```

`Cargo.toml`:
```toml
[package]
name = "testing"
version = "0.1.0"
edition = "2018"

[dependencies]
thiserror = "1.0.25"
```
Of course, it should be noted that `cargo check`, `cargo clippy` and `cargo build` work without any errors.

Version info:
`cargo version`: `cargo 1.55.0-nightly (3ebb5f15a 2021-07-02)`
