### ISSUE TITLE
[2021-07-26 stable] `unresolved extern crate` found on `use` in small project

### ISSUE THREAD

**Issue by dennismayr** [rust-analyzer/rust-analyzer#9723]
Hello!

Yesterday, I found that an apparent false-positive shows up when creating a `Rocket` project in Emacs (version 27.2 + _lsp_).
I'm using the `rust stable` _1.53_ toolchain and `rust-analyzer` _2021-07-26 stable_

Here's a short example:

- Create a test project, e.g. `cargo new --bin hello_rocket; cd hello_rocket`
- Edit _Cargo.toml:_
```toml
[package]
name = "hello_rocket"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc"
serde = "1.0"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc"
features = ["handlebars"]
```
The project runs on the `stable` toolchain.

- Edit _src/main.rs:_
```rust
extern crate rocket;
extern crate rocket_dyn_templates;

use rocket::*;
use rocket_dyn_templates::Template;

#[get("/")]
fn index() -> Template {
    Template::render("index", &())
}

#[launch]
fn rocket() -> _ {
    rocket::build()
        .attach(Template::fairing())
        .mount("/", routes![index])
}
```

You'll see that the 4th line, `use rocket_dyn_templates::Template;` triggers an `unresolved extern crate` warning.
Here's the official documentation on how to implement the apparently incorrect line: [rocket_dyn_templates](https://api.rocket.rs/master/rocket_dyn_templates/struct.Template.html)

However, `cargo run` does not show any errors on compilation.
