### ISSUE TITLE
tokio::test fn not recognized as a test when procedural macros are enabled

### ISSUE THREAD

**Issue by aymarino** [rust-analyzer/rust-analyzer#9935]
Here is a minimal example:

```rust
fn main() {}

#[cfg(test)]
mod tests {
    #[test] // 'Run Test' tooltip always shown
    fn test_one() {}

    #[tokio::test] // 'Run Test' not shown when Proc Macros enabled
    async fn test_two() {}
}
```

Cargo.toml dependencies:
```toml
[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
```

Like the title/code snippet says, when the Procedural Macros feature is disabled, both tests are recognized just fine and can be run from the UI action, but when Proc Macros are enabled, the `tokio::test` fn is not recognized as a test. Note that `tokio::test` is itself a procedural macro.
